import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className='bg-white min-h-screen overflow-auto w-full'>{children}</body>
    </html>
  );
}
